import { create } from "ipfs-http-client";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import Web3 from "web3";
import Navbar from "../../components/Navbar";
import { useData } from "../../contexts/DataContext";

const Admin = () => {
  const router = useRouter();
  const { polymarket, polyToken, loadWeb3, account } = useData!();
  const [loading, setLoading] = React.useState(false);
  const client = create({ url: "https://ipfs.infura.io:5001/api/v0" });

  const [title, setTitle] = React.useState("");
  const [description, setDescription] = React.useState("");
  const [imageHash, setImageHash] = React.useState("");
  const [resolverUrl, setResolverUrl] = React.useState("");
  const [timestamp, setTimestamp] = React.useState<
    string | number | readonly string[] | undefined
  >(Date());

  // Manual top-up form state (admin credits a user's internal wallet by minting POLY)
  const [topUpAddress, setTopUpAddress] = React.useState("");
  const [topUpAmount, setTopUpAmount] = React.useState("");
  const [topUpLoading, setTopUpLoading] = React.useState(false);

  const uploadImage = async (e: any) => {
    const file = e.target.files[0];
    const added = await client.add(file);
    setImageHash(added.path);
  };

  useEffect(() => {
    loadWeb3();
  }, [loading]);

  const handleTopUp = async () => {
    if (!polyToken || !account) return;
    if (!topUpAddress || !topUpAmount) return;

    try {
      setTopUpLoading(true);
      await polyToken.methods
        .mint(topUpAddress, Web3.utils.toWei(topUpAmount, "ether"))
        .send({ from: account });
      setTopUpAmount("");
      setTopUpAddress("");
    } finally {
      setTopUpLoading(false);
    }
  };

  const handleSubmit = async () => {
    setLoading(true);
    await polymarket.methods
      .createQuestion(title, imageHash, description, resolverUrl, timestamp)
      .send({
        from: account,
      });
    setLoading(false);
    setTitle("");
    setDescription("");
    setImageHash("");
    setResolverUrl("");
    setTimestamp(undefined);
    router.push("/");
  };

  return (
    <>
      <div className="flex flex-col justify-center items-center h-full p-5 bg-gray-50">
        <Head>
          <title>Polymarket</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <main className="w-full flex flex-col py-6 max-w-5xl pb-6 space-y-6">
          <div className="flex flex-col space-y-3 mb-1">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-lg font-semibold text-gray-900">
                  Admin Console
                </h1>
                <p className="text-xs text-gray-600 mt-0.5">
                  Manage markets, funding and settlement using your admin keys.
                </p>
              </div>
              <Link href="/admin/markets">
                <a className="hidden sm:inline-flex items-center rounded-full h-9 px-4 text-xs font-medium cta-primary text-white shadow-brand-card">
                  View &amp; resolve markets
                </a>
              </Link>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="rounded-lg bg-white border border-gray-200 px-3 py-3 flex flex-col">
                <span className="text-[11px] uppercase tracking-wide text-gray-500">
                  Environment
                </span>
                <span className="mt-1 text-sm font-medium text-gray-900">
                  Local Ganache
                </span>
              </div>
              <div className="rounded-lg bg-white border border-gray-200 px-3 py-3 flex flex-col">
                <span className="text-[11px] uppercase tracking-wide text-gray-500">
                  Funding mode
                </span>
                <span className="mt-1 text-sm font-medium text-gray-900">
                  Manual top ups
                </span>
              </div>
              <div className="rounded-lg bg-white border border-gray-200 px-3 py-3 flex flex-col">
                <span className="text-[11px] uppercase tracking-wide text-gray-500">
                  Admin address
                </span>
                <span className="mt-1 text-xs number-mono text-gray-900 truncate">
                  {account || "Not connected"}
                </span>
              </div>
            </div>
          </div>
          <Link href="/admin/markets">
            <a className="sm:hidden mt-1 rounded-full py-2.5 text-center w-full cta-primary text-white font-semibold shadow-brand-card text-xs tracking-wide">
              View &amp; resolve markets
            </a>
          </Link>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <div className="w-full flex flex-col border border-gray-200 p-5 rounded-xl bg-white shadow-sm">
              <span className="text-[11px] font-semibold uppercase tracking-widest text-gray-600">
                Treasury
              </span>
              <span className="text-lg font-semibold mt-1 text-gray-900">
                Top up user wallet (POLY)
              </span>
              <span className="text-xs text-gray-600 mt-2">
                After receiving payment via mobile money, card, or other
                methods, credit the user&apos;s on-chain POLY balance.
              </span>
              <span className="text-xs text-yellow-700 mt-3">
                You must be connected with the deployer/owner account of the
                POLY token contract.
              </span>
              <span className="text-xs font-semibold mt-6 mb-1 text-gray-700">
                User address
              </span>
              <input
                type="input"
                name="topUpAddress"
                value={topUpAddress}
                onChange={(e) => setTopUpAddress(e.target.value)}
                className="w-full py-2.5 px-3 text-sm text-gray-900 bg-white rounded-md focus:outline-none border border-gray-300 focus:ring-2 focus:ring-cyanbrand focus:ring-opacity-80"
                placeholder="0x..."
                autoComplete="off"
              />
              <span className="text-xs font-semibold mt-4 mb-1 text-gray-700">
                Amount (POLY)
              </span>
              <input
                type="number"
                min="0"
                step="0.0001"
                name="topUpAmount"
                value={topUpAmount}
                onChange={(e) => setTopUpAmount(e.target.value)}
                className="w-full py-2.5 px-3 text-sm text-gray-900 bg-white rounded-md focus:outline-none border border-gray-300 focus:ring-2 focus:ring-cyanbrand focus:ring-opacity-80 number-mono"
                placeholder="Amount in POLY"
                autoComplete="off"
              />
              <button
                className="mt-5 rounded-md py-2.5 text-center w-full bg-cobalt text-white font-medium shadow-sm disabled:opacity-60 text-sm tracking-wide hover:bg-lapis transition-colors"
                onClick={handleTopUp}
                disabled={topUpLoading}
              >
                {topUpLoading ? "Processing..." : "Top up wallet"}
              </button>
            </div>
            <div className="w-full flex flex-col border border-gray-200 p-5 rounded-xl bg-white shadow-sm">
              <span className="text-[11px] font-semibold uppercase tracking-widest text-gray-600">
                Markets
              </span>
              <span className="text-lg font-semibold mt-1 text-gray-900">
                Create new market
              </span>
              <span className="text-xs text-gray-600 mt-2">
                Configure question text, image, resolution source and end date.
              </span>
              <span className="text-xs font-semibold mt-6 mb-1 text-gray-700">
                Market title
              </span>
              <input
                type="input"
                name="title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full py-2.5 px-3 text-sm text-gray-900 bg-white rounded-md focus:outline-none border border-gray-300 focus:ring-2 focus:ring-cyanbrand focus:ring-opacity-80"
                placeholder="Title"
                autoComplete="off"
              />
              <span className="text-xs font-semibold mt-4 mb-1 text-gray-700">
                Market description
              </span>
              <textarea
                name="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="w-full py-2.5 px-3 text-sm text-gray-900 bg-white rounded-md focus:outline-none border border-gray-300 focus:ring-2 focus:ring-cyanbrand focus:ring-opacity-80 min-h-[110px]"
                placeholder="Description"
                autoComplete="off"
              ></textarea>
              <span className="text-xs font-semibold mt-4 mb-1 text-gray-700">
                Market image
              </span>
              <div className="mt-1 flex items-center space-x-3">
                <label className="inline-flex items-center justify-center px-3 py-2 rounded-md border border-gray-300 bg-white text-xs font-medium text-gray-800 cursor-pointer hover:bg-gray-50 hover:border-cobalt transition-colors">
                  Choose file
                  <input
                    type="file"
                    onChange={uploadImage}
                    className="hidden"
                  />
                </label>
                <span className="text-[11px] text-gray-500">
                  Upload a square image for the market card.
                </span>
              </div>
              <span className="text-xs font-semibold mt-4 mb-1 text-gray-700">
                Resolve URL
              </span>
              <input
                type="input"
                name="resolverUrl"
                value={resolverUrl}
                onChange={(e) => setResolverUrl(e.target.value)}
                className="w-full py-2.5 px-3 text-sm text-gray-900 bg-white rounded-md focus:outline-none border border-gray-300 focus:ring-2 focus:ring-cyanbrand focus:ring-opacity-80"
                placeholder="URL"
                autoComplete="off"
              />
              <span className="text-xs font-semibold mt-4 mb-1 text-gray-700">
                End date
              </span>
              <input
                type="date"
                name="timestamp"
                // value={timestamp}
                onChange={(e) => {
                  setTimestamp(e.target.valueAsDate?.getTime());
                }}
                className="w-full py-2.5 px-3 text-sm text-gray-900 bg-white rounded-md focus:outline-none border border-gray-300 focus:ring-2 focus:ring-cyanbrand focus:ring-opacity-80"
                autoComplete="off"
              />
              {loading ? (
                <span className="text-center pt-4 pb-2 text-sm font-medium text-cobalt">
                  Creating market...
                </span>
              ) : (
                <button
                  className="mt-5 rounded-md py-2.5 text-center w-full bg-cobalt text-white font-medium shadow-sm text-sm tracking-wide hover:bg-lapis transition-colors"
                  onClick={() => {
                    handleSubmit();
                  }}
                >
                  Create market
                </button>
              )}
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Admin;
